import { translate } from 'typed-intl'

export const AccountDataMsg = translate({
    update: 'Mettre à jour le profil',
    title: 'Données personnelles',
    submit: 'Enregistrer',
    firstName: 'Prénom ::',
    lastName: 'Nom ::',
    phone: 'Téléphone ::',
    zipCode: 'Code postal ::',
    city: 'Ville ::',
    address: 'Adresse ::',
    age: 'Age ::',
    email: 'Email ::',
    gender: 'Titre ::',
    username: `Nom d'utilisateur ::`,
    msgFN: 'Veuillez saisir votre prénom',
    msgLN: 'Veuillez saisir votre nom',
    msgP: 'Veuillez saisir votre téléphone',
    msgZ: 'Veuillez saisir votre code postal',
    msgC: 'Veuillez saisir votre ville',
    msgAddress: 'Veuillez saisir votre adresse',
    msgAge: 'Veuillez saisir votre age',
    msgE: 'Veuillez saisir votre email',
    msgG: 'Veuillez saisir votre titre',
    msgU: `Veuillez saisir votre nom d'utilisateur`
}).supporting('en', {
    update: 'Update profil',
    title: 'Personal data',
    submit: 'Save',
    firstName: 'FirstName ::',
    lastName: 'LastName ::',
    phone: 'Phone ::',
    zipCode: 'Zip code ::',
    city: 'City ::',
    address: 'Address ::',
    age: 'Age ::',
    email: 'Email ::',
    gender: 'Gender ::',
    username: 'Username ::',
    msgFN: 'Please input your first name',
    msgLN: 'Please input your last name',
    msgP: 'Please input your phone',
    msgZ: 'Please input your zipCode',
    msgC: 'Please input your city',
    msgAddress: 'Please input your address',
    msgAge: 'Please input your age',
    msgE: 'Please input your email',
    msgG: 'Please input your title',
    msgU: 'Please input your username'
})